# Generated by Django 4.1.3 on 2022-11-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('edad', models.IntegerField(max_length=3, verbose_name='Edad')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('padecimientos', models.CharField(max_length=50, verbose_name='Padecimientos')),
                ('fecha', models.DateField(auto_now=True, verbose_name='FechaActual')),
            ],
            options={
                'verbose_name': 'hojacargo',
                'verbose_name_plural': 'hojacargos',
            },
        ),
        migrations.CreateModel(
            name='InformePCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fechais', models.DateField(verbose_name='FechaIS')),
                ('fechatm', models.DateField(verbose_name='FechaTM')),
                ('consultorio', models.IntegerField(verbose_name='Consultorio')),
                ('resultado', models.BooleanField(verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'InformePCR',
                'verbose_name_plural': 'InformePCRs',
            },
        ),
    ]
