# Generated by Django 4.1.3 on 2022-12-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('ci', models.IntegerField(verbose_name='CI')),
                ('departamento', models.CharField(max_length=50, verbose_name='departamento')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
            options={
                'verbose_name': 'NuevoUser',
                'verbose_name_plural': 'NuevoUsers',
            },
        ),
        migrations.AlterModelOptions(
            name='hojacargo',
            options={'verbose_name': 'hoja de cargo', 'verbose_name_plural': 'hojas de cargo'},
        ),
        migrations.AlterField(
            model_name='hojacargo',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
