# Generated by Django 4.1.3 on 2022-12-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nuevouser_alter_hojacargo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informepcr',
            options={'verbose_name': 'Informe PCR', 'verbose_name_plural': 'Informes PCR'},
        ),
        migrations.AddField(
            model_name='informepcr',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='FechaActual'),
        ),
        migrations.AlterField(
            model_name='informepcr',
            name='resultado',
            field=models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=1, verbose_name='Resultado'),
        ),
    ]
