# Generated by Django 4.1.3 on 2022-12-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_delete_nuevouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
